version: "3.3"
services:
  pihole:
    container_name: pihole_prod
    image: pihole/pihole:latest
    ports:
      - 5300:53/tcp
      - 5300:53/udp
      - 8081:80/tcp
    networks:
      doh_net:
        ipv4_address: 172.18.1.2
    environment:
      TZ: Asia/Tehran
      VIRTUAL_HOST: REPLCAE_YOUR_DOMAIN # domain name well use for our DNS serv$
      WEBPASSWORD: PIHOLE_ADMIN_PASS # Pihole admin password
    volumes:
      - ./pihole/data/etc-pihole/:/etc/pihole/
      - ./pihole/data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
  dnsdist:
    container_name: dnsdist_prod
    build:
      context: dnsdist
      dockerfile: Dockerfile
    image: dnsdist:prod
    tty: true
    stdin_open: true
    ports:
      - 443:443/tcp
      - 853:853/tcp
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Asia/Tehran
      SNI_ADDRESS: REPLACE_YOUR_DOMAIN
    depends_on:
      - pihole
    networks:
      doh_net:
        ipv4_address: 172.18.1.3
    volumes:
      - CERTIFICATE_PATH:/etc/dnsdist/fullchain.pem:ro
      - CERTIFICATE_PRIVATEKEY_PATH:/etc/dnsdist/privkey.pem:ro
    restart: unless-stopped

networks:
  doh_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.1.0/29
